name: 'loganbickmore/rpmbuild'
description: 'Build RPM packages'
author: 'loganbickmore'
inputs:
  spec_file:
    description: 'path to spec file'
    required: true
    default: '*.spec'
  src_archive:
    description: 'path to source archive file'
    required: true
outputs:
  rpm_name:
    description: 'name of rpm file, taken from path'
  rpm_path:
    description: 'path to rpm file'
  rpm_content_type:
    description: 'content-type of rpm file'

runs:
  using: 'docker'
  image: 'Dockerfile'
